### ISSUE TITLE
[Feature] 몬스터 스탯 추가

### ISSUE THREAD

**Issue by Qyubee99** [KIA-PROGRAMMING-38/The-Binding-of-Isaac#17]
몬스터는 각자에 맞는 체력과 공격력이 있습니다.
ex) 전투형 파리 : 체력 5, 공격력 0.5 , 게이퍼 : 체력 10, 공격력 0.5 등등
일반 몬스터의 공격은 플레이어의 체력을 반칸(0.5) 감소시킵니다.
보스의 공격은 플레이어의 체력을 한칸(1) 감소시킵니다.

**Comment by ChoiSeonMun** [comment]
#12 랑 통합할 것
