### ISSUE TITLE
[Feature] 플레이어의 피격 및 사망 애니메이션 추가

### ISSUE THREAD

**Issue by Qyubee99** [KIA-PROGRAMMING-38/The-Binding-of-Isaac#18]
플레이어는 피격을 당할 시 피격 애니메이션이 재생되고 1초 동안 무적 상태가 됩니다.(깜빡 깜빡 거림)
플레이어의 체력이 0이 될 경우 사망 애니메이션이 재생되고 게임 오버 됩니다.
![플레이어 피격모션 및 사망모션](https://user-images.githubusercontent.com/101865591/231087291-a2fbc080-07ee-403b-9268-bad4e154d816.gif)

**Comment by ChoiSeonMun** [comment]
몬스터랑 플레이어 나눌 것
